### ISSUE TITLE
Can the strip method return a Vec<u8>?

### ISSUE THREAD

**Issue by sunshowers** [luser/strip-ansi-escapes#9]
https://docs.rs/strip-ansi-escapes/latest/strip_ansi_escapes/fn.strip.html

Looks like it currently returns an `io::Result<Vec<u8>>`. Given that the writer is just a `Cursor<Vec<u8>>`, it seems like the strip method can `expect` that writing never fails.

**Comment by luser** [comment]
I suspect so? It's written the way it is because the `Writer` is generic over an underlying `io::Write` implementation, so it propagates errors upwards. If you want to rework the internal abstractions a bit, I'm open to suggestions. I wrote this crate to spec for `sccache`'s use case of "I have cached program output that might contain escape sequences, and I need to write it without them", so the streaming API makes the most sense for that.

**Comment by sunshowers** [comment]
Oh I was just thinking of throwing an except() in there

**Comment by luser** [comment]
Oh, that seems fine. :)
